sudo: false
language: ruby
bundler_args: --path vendor/bundle --jobs=3 --retry=3
script:
  - bundle exec rspec
  - bundle exec ruby -Ilib bin/metric_fu
  - bundle exec rubocop
  - bundle exec rake

cache: bundler

before_install:
  - gem install bundler
  - bundle config --local without local_development yard guard
rvm:
  # 2.1, not 2.1.0 until fixed https://github.com/travis-ci/travis-ci/issues/2220
  - 2.3.1
  - 2.2.5
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.2
  - 1.9.3
  - jruby
  - "rbx-2"
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
