sudo: false
language: ruby
bundler_args: --path vendor/bundle --jobs=3 --retry=3
script: bundle exec rspec
cache: bundler

before_install:
  - gem install bundler -v 1.13.7
  - bundle config --local without local_development yard guard

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby

matrix:
  allow_failures:
  fast_finish: true
